# Generated by Django 4.0.6 on 2022-07-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemsModel',
            new_name='expenseModel',
        ),
    ]
