# Generated by Django 4.0.6 on 2022-07-29 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_itemsmodel_expensemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='name',
            new_name='expense',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='number',
            new_name='value',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
