# Generated by Django 4.0.6 on 2022-08-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expensemodel_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='TransType',
            field=models.CharField(default='expense', max_length=30),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
