# Generated by Django 4.0.6 on 2022-08-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensemodel_transtype_alter_expensemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
